name: Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Set your Node.js version
          cache: 'npm' # Use 'yarn' or 'pnpm' if needed

      - name: Install dependencies
        run: npm ci # Ensures a clean install

      - name: Run build
        run: npm run build

      # - name: Run tests (optional)
      #   run: npm test
